name: Publish image

env:
  DOTNET_VERSION: "6.0.x"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/kevinhu/pgsearch:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

    #   - name: "Build Inventory Image"
    #     run: |
    #       docker build . --tag ghcr.io/kevinhu/pgsearch:latest
    #       docker push ghcr.io/kevinhu/pgsearch:latest
